/*
 * This file is generated by jOOQ.
*/
package box.white.seriwb.api.jooq.public_;


import box.white.seriwb.api.jooq.public_.tables.Sample;
import box.white.seriwb.api.jooq.public_.tables.records.SampleRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SampleRecord, Long> IDENTITY_SAMPLE = Identities0.IDENTITY_SAMPLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SampleRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<SampleRecord, Long> IDENTITY_SAMPLE = createIdentity(Sample.SAMPLE, Sample.SAMPLE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<SampleRecord> CONSTRAINT_9 = createUniqueKey(Sample.SAMPLE, "CONSTRAINT_9", Sample.SAMPLE.ID);
    }
}
