/*
 * This file is generated by jOOQ.
*/
package box.white.seriwb.api.jooq.public_;


import box.white.seriwb.api.jooq.public_.tables.Sample;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.SAMPLE</code>.
     */
    public static final Sample SAMPLE = box.white.seriwb.api.jooq.public_.tables.Sample.SAMPLE;
}
