/*
 * This file is generated by jOOQ.
*/
package box.white.seriwb.api.jooq.information_schema;


import box.white.seriwb.api.jooq.information_schema.tables.Catalogs;
import box.white.seriwb.api.jooq.information_schema.tables.Collations;
import box.white.seriwb.api.jooq.information_schema.tables.ColumnPrivileges;
import box.white.seriwb.api.jooq.information_schema.tables.Columns;
import box.white.seriwb.api.jooq.information_schema.tables.Constants;
import box.white.seriwb.api.jooq.information_schema.tables.Constraints;
import box.white.seriwb.api.jooq.information_schema.tables.CrossReferences;
import box.white.seriwb.api.jooq.information_schema.tables.Domains;
import box.white.seriwb.api.jooq.information_schema.tables.FunctionAliases;
import box.white.seriwb.api.jooq.information_schema.tables.FunctionColumns;
import box.white.seriwb.api.jooq.information_schema.tables.Help;
import box.white.seriwb.api.jooq.information_schema.tables.InDoubt;
import box.white.seriwb.api.jooq.information_schema.tables.Indexes;
import box.white.seriwb.api.jooq.information_schema.tables.Locks;
import box.white.seriwb.api.jooq.information_schema.tables.QueryStatistics;
import box.white.seriwb.api.jooq.information_schema.tables.Rights;
import box.white.seriwb.api.jooq.information_schema.tables.Roles;
import box.white.seriwb.api.jooq.information_schema.tables.Schemata;
import box.white.seriwb.api.jooq.information_schema.tables.Sequences;
import box.white.seriwb.api.jooq.information_schema.tables.SessionState;
import box.white.seriwb.api.jooq.information_schema.tables.Sessions;
import box.white.seriwb.api.jooq.information_schema.tables.Settings;
import box.white.seriwb.api.jooq.information_schema.tables.TablePrivileges;
import box.white.seriwb.api.jooq.information_schema.tables.TableTypes;
import box.white.seriwb.api.jooq.information_schema.tables.Triggers;
import box.white.seriwb.api.jooq.information_schema.tables.TypeInfo;
import box.white.seriwb.api.jooq.information_schema.tables.Users;
import box.white.seriwb.api.jooq.information_schema.tables.Views;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>INFORMATION_SCHEMA.CATALOGS</code>.
     */
    public static final Catalogs CATALOGS = box.white.seriwb.api.jooq.information_schema.tables.Catalogs.CATALOGS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLLATIONS</code>.
     */
    public static final Collations COLLATIONS = box.white.seriwb.api.jooq.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMNS</code>.
     */
    public static final Columns COLUMNS = box.white.seriwb.api.jooq.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMN_PRIVILEGES</code>.
     */
    public static final ColumnPrivileges COLUMN_PRIVILEGES = box.white.seriwb.api.jooq.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTANTS</code>.
     */
    public static final Constants CONSTANTS = box.white.seriwb.api.jooq.information_schema.tables.Constants.CONSTANTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTRAINTS</code>.
     */
    public static final Constraints CONSTRAINTS = box.white.seriwb.api.jooq.information_schema.tables.Constraints.CONSTRAINTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CROSS_REFERENCES</code>.
     */
    public static final CrossReferences CROSS_REFERENCES = box.white.seriwb.api.jooq.information_schema.tables.CrossReferences.CROSS_REFERENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.DOMAINS</code>.
     */
    public static final Domains DOMAINS = box.white.seriwb.api.jooq.information_schema.tables.Domains.DOMAINS;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_ALIASES</code>.
     */
    public static final FunctionAliases FUNCTION_ALIASES = box.white.seriwb.api.jooq.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_COLUMNS</code>.
     */
    public static final FunctionColumns FUNCTION_COLUMNS = box.white.seriwb.api.jooq.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.HELP</code>.
     */
    public static final Help HELP = box.white.seriwb.api.jooq.information_schema.tables.Help.HELP;

    /**
     * The table <code>INFORMATION_SCHEMA.INDEXES</code>.
     */
    public static final Indexes INDEXES = box.white.seriwb.api.jooq.information_schema.tables.Indexes.INDEXES;

    /**
     * The table <code>INFORMATION_SCHEMA.IN_DOUBT</code>.
     */
    public static final InDoubt IN_DOUBT = box.white.seriwb.api.jooq.information_schema.tables.InDoubt.IN_DOUBT;

    /**
     * The table <code>INFORMATION_SCHEMA.LOCKS</code>.
     */
    public static final Locks LOCKS = box.white.seriwb.api.jooq.information_schema.tables.Locks.LOCKS;

    /**
     * The table <code>INFORMATION_SCHEMA.QUERY_STATISTICS</code>.
     */
    public static final QueryStatistics QUERY_STATISTICS = box.white.seriwb.api.jooq.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

    /**
     * The table <code>INFORMATION_SCHEMA.RIGHTS</code>.
     */
    public static final Rights RIGHTS = box.white.seriwb.api.jooq.information_schema.tables.Rights.RIGHTS;

    /**
     * The table <code>INFORMATION_SCHEMA.ROLES</code>.
     */
    public static final Roles ROLES = box.white.seriwb.api.jooq.information_schema.tables.Roles.ROLES;

    /**
     * The table <code>INFORMATION_SCHEMA.SCHEMATA</code>.
     */
    public static final Schemata SCHEMATA = box.white.seriwb.api.jooq.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>INFORMATION_SCHEMA.SEQUENCES</code>.
     */
    public static final Sequences SEQUENCES = box.white.seriwb.api.jooq.information_schema.tables.Sequences.SEQUENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSIONS</code>.
     */
    public static final Sessions SESSIONS = box.white.seriwb.api.jooq.information_schema.tables.Sessions.SESSIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSION_STATE</code>.
     */
    public static final SessionState SESSION_STATE = box.white.seriwb.api.jooq.information_schema.tables.SessionState.SESSION_STATE;

    /**
     * The table <code>INFORMATION_SCHEMA.SETTINGS</code>.
     */
    public static final Settings SETTINGS = box.white.seriwb.api.jooq.information_schema.tables.Settings.SETTINGS;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLES</code>.
     */
    public static final box.white.seriwb.api.jooq.information_schema.tables.Tables TABLES = box.white.seriwb.api.jooq.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_PRIVILEGES</code>.
     */
    public static final TablePrivileges TABLE_PRIVILEGES = box.white.seriwb.api.jooq.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_TYPES</code>.
     */
    public static final TableTypes TABLE_TYPES = box.white.seriwb.api.jooq.information_schema.tables.TableTypes.TABLE_TYPES;

    /**
     * The table <code>INFORMATION_SCHEMA.TRIGGERS</code>.
     */
    public static final Triggers TRIGGERS = box.white.seriwb.api.jooq.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>INFORMATION_SCHEMA.TYPE_INFO</code>.
     */
    public static final TypeInfo TYPE_INFO = box.white.seriwb.api.jooq.information_schema.tables.TypeInfo.TYPE_INFO;

    /**
     * The table <code>INFORMATION_SCHEMA.USERS</code>.
     */
    public static final Users USERS = box.white.seriwb.api.jooq.information_schema.tables.Users.USERS;

    /**
     * The table <code>INFORMATION_SCHEMA.VIEWS</code>.
     */
    public static final Views VIEWS = box.white.seriwb.api.jooq.information_schema.tables.Views.VIEWS;
}
