/*
 * This file is generated by jOOQ.
*/
package box.white.seriwb.api.jooq.public_.tables;


import box.white.seriwb.api.jooq.public_.Indexes;
import box.white.seriwb.api.jooq.public_.Keys;
import box.white.seriwb.api.jooq.public_.Public;
import box.white.seriwb.api.jooq.public_.tables.records.SampleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sample extends TableImpl<SampleRecord> {

    private static final long serialVersionUID = -2095614301;

    /**
     * The reference instance of <code>PUBLIC.SAMPLE</code>
     */
    public static final Sample SAMPLE = new Sample();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SampleRecord> getRecordType() {
        return SampleRecord.class;
    }

    /**
     * The column <code>PUBLIC.SAMPLE.ID</code>.
     */
    public final TableField<SampleRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.SAMPLE.KEY</code>.
     */
    public final TableField<SampleRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>PUBLIC.SAMPLE.VALUE</code>.
     */
    public final TableField<SampleRecord, String> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * Create a <code>PUBLIC.SAMPLE</code> table reference
     */
    public Sample() {
        this(DSL.name("SAMPLE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.SAMPLE</code> table reference
     */
    public Sample(String alias) {
        this(DSL.name(alias), SAMPLE);
    }

    /**
     * Create an aliased <code>PUBLIC.SAMPLE</code> table reference
     */
    public Sample(Name alias) {
        this(alias, SAMPLE);
    }

    private Sample(Name alias, Table<SampleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sample(Name alias, Table<SampleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SampleRecord, Long> getIdentity() {
        return Keys.IDENTITY_SAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SampleRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SampleRecord>> getKeys() {
        return Arrays.<UniqueKey<SampleRecord>>asList(Keys.CONSTRAINT_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sample as(String alias) {
        return new Sample(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sample as(Name alias) {
        return new Sample(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sample rename(String name) {
        return new Sample(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sample rename(Name name) {
        return new Sample(name, null);
    }
}
